export const TokenOverviewListItems = [
  {
    platform: 'MEXC',
    platform_img: 'mexc.svg',
    desc: 'Buy/Trade PCR',
    type: 'CEX',
    chain_img: '',
    chain: 'none',
    infoLink: 'https://paycerprotocol.medium.com/paycer-pcr-token-cex-listing-on-mexc-cacdf5cfd674',
    link: 'https://www.mexc.com/exchange/PCR_USDT',
  },
  {
    platform: 'Coinmarketcap',
    platform_img: 'cmc.svg',
    desc: 'Charts/Price',
    type: 'Info',
    chain_img: '',
    chain: 'Coinmarketcap CMC coin',
    infoLink: 'https://coinmarketcap.com/currencies/paycer-protocol/',
    link: 'https://coinmarketcap.com/currencies/paycer-protocol/',
  },
  {
    platform: 'DODO',
    platform_img: 'dodo.svg',
    desc: 'Buy/Trade PCR',
    type: 'DEX',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycerprotocol.medium.com/paycer-update-migration-of-pcr-pools-from-uniswap-to-dodo-8a879a4f6f1d',
    link: 'https://app.dodoex.io/exchange/PCR-USDC?network=polygon',
  },
  {
    platform: 'DODO',
    platform_img: 'dodo.svg',
    desc: 'Liquidity Mining PCR/USDT',
    type: 'Rewards',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycerprotocol.medium.com/paycer-update-migration-of-pcr-pools-from-uniswap-to-dodo-8a879a4f6f1d',
    link: 'https://app.dodoex.io/earn/add-liquidity?network=polygon&poolAddress=0xfe9ff05a9fdf1f3e42fee39ee5a9e2205d8e7521&forced=true',
  },
  {
    platform: 'DODO',
    platform_img: 'dodo.svg',
    desc: 'Liquidity Mining PCR/USDC',
    type: 'Rewards',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycerprotocol.medium.com/paycer-update-migration-of-pcr-pools-from-uniswap-to-dodo-8a879a4f6f1d',
    link: 'https://app.dodoex.io/earn/add-liquidity?network=polygon&poolAddress=0x0dd9b3a37548bc90e7231918547b8da55572f37f&forced=true',
  },
  {
    platform: 'Paycer Finance',
    platform_img: 'paycer.svg',
    desc: 'PCR Token Staking',
    type: 'Rewards',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/staking',
    link: 'https://paycer.finance/staking',
  },
  {
    platform: 'UniFarm',
    platform_img: 'unifarm.svg',
    desc: 'Staking / Farming',
    type: 'Rewards',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycerprotocol.medium.com/paycer-partnered-with-unifarm-part-of-cohort-35-a4d05cfe3c3a',
    link: 'https://blog.unifarm.co/how-to-stake-tokens-on-unifarm/',
  },
  {
    platform: 'Paycer Finance',
    platform_img: 'paycer.svg',
    desc: 'PCR Token Vesting',
    type: 'Vesting',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/token-vesting',
    link: 'https://paycer.finance/vesting',
  },
  {
    platform: 'Paycer Finance',
    platform_img: 'paycer.svg',
    desc: 'PCR Token Burn',
    type: 'Burning',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycerprotocol.medium.com/announcement-massive-30m-pcr-token-burn-92fb696c145c',
    link: 'https://paycer.gitbook.io/paycer/paycer-token/token-burn',
  },
  {
    platform: 'Polygon',
    platform_img: 'polygon.svg',
    desc: 'PCR Token Contract',
    type: 'Contract',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon Matic',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/smart-contracts',
    link: 'https://polygonscan.com/address/0xa6083abe845fbB8649d98B8586cBF50b7f233612',
  },
  {
    platform: 'Binance Smart Chain',
    platform_img: 'binance.svg',
    desc: 'PCR Token Contract',
    type: 'Contract',
    chain_img: 'binance_chain.svg',
    chain: 'BSC Binance Smart Chain',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/smart-contracts',
    link: 'https://bscscan.com/address/0xa9f31589E0a8c0b12068329736ed6385A8F77b62',
  },
  {
    platform: 'Avalanche',
    platform_img: 'avalanche.svg',
    desc: 'PCR Token Contract',
    type: 'Contract',
    chain_img: 'avalanche_chain.svg',
    chain: 'avalanche avax',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/smart-contracts',
    link: 'https://snowtrace.io/address/0xa9f31589e0a8c0b12068329736ed6385a8f77b62',
  },
  {
    platform: 'Ethereum',
    platform_img: 'ethereum.svg',
    desc: 'PCR Token Contract',
    type: 'Contract',
    chain_img: 'ethereum_chain.svg',
    chain: 'Ethereum',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/smart-contracts',
    link: 'https://etherscan.io/address/0x24FdBF97A95d425E2e53D1d35C4920c82Ba784f1',
  },
  {
    platform: 'Paycer Finance',
    platform_img: 'paycer.svg',
    desc: 'PCR Tokenomics',
    type: 'Info',
    chain_img: 'polygon_chain.svg',
    chain: 'Polygon',
    infoLink: 'https://paycer.gitbook.io/paycer/paycer-token/tokenomics',
    link: 'https://paycer.gitbook.io/paycer/paycer-token/tokenomics',
  },
]
